### ISSUE TITLE
Broken if guards containing try expressions

### ISSUE THREAD

**Issue by GrahamCampbell** [UoYCS-plasma/GP2#28]
Consider the following input graph: `[ (0, 0 # grey) |  ]`.

One would expect the following program to pass, writing as output `[ (0, 0) |  ]`:

```
Main = try unmark; if check then fail

unmark(x: list)
[ (n1, x # grey) | ]
=>
[ (n1, x) | ]
interface = {n1}

check(x,y: list)
[ (n1, x) (n2, y) | ]
=>
[ (n1, x) (n2, y) | ]
interface = {n1, n2}
```

And it does... but now consider the same program, but replace `Main` with:

```
Main = if (try unmark; check) then fail
```

One would expect an output graph of `[ (0, 0 # grey) |  ]`, however instead, **the program fails**! This is not correct behaviour.

---

This bug is present in both the `legacy` and `master` versions of the compiler.

**Comment by jackromo** [comment]
The generated code for the `if` statement above in the second case is shown here from the `legacy` compiler, in the generated `main.c`:

`   do
   {
      /* Try Statement */
      /* Condition */
      do
      {
         /* Rule Call */
         if(matchMain_unmark(M_Main_unmark))
         {
            applyMain_unmark(M_Main_unmark, true);
            success = true;
         }
         else
         {
            success = false;
            break;
         }
      } while(false);

      /* Then Branch */
      if(success)
      {
         /* Skip Statement */
         success = true;
      }
      /* Else Branch */
      else
      {
         success = true;
         /* Skip Statement */
         success = true;
      }
      break;
      /* Rule Call */
      if(matchMain_check(M_Main_check))
      {
         success = true;
      }
      else
      {
         success = false;
         break;
      }
   } while(false);`

It seems that a `break` statement after the penultimate `else` clause stops the `check` rule from ever possibly running, with `success == true` at the end no matter what.

I imagine the penultimate `else` clause above is erroneously generated. The code responsible is lines 600 to 624 in `src/genProgram.c` in the `legacy` compiler.

**Comment by GrahamCampbell** [comment]
I am going to go ahead an apply the suggested fix. I'm not aware of any programs that are broken by this.
