### ISSUE TITLE
Typo in README.md?

### ISSUE THREAD

**Issue by kolovos** [UoYCS-plasma/GP2#32]
To run the transitive closure example in [README.md](https://github.com/UoYCS-plasma/GP2/blob/master/README.md), I had to change `where not edge(1, 3)` to `where not edge(n1, n3)` as gp2docker would otherwise produce the following error message:

```
Error (Main_link): Node 1 in edge predicate not in the interface.
Error (Main_link): Node 3 in edge predicate not in the interface.
```

**Comment by rsoeldner** [comment]
Good catch, this is indeed a typo. The edge ids start, in this particular case, with `n`.
